-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 11:37:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendas_sucos` DEFAULT CHARACTER SET utf8mb4 ;
USE `vendas_sucos` ;

-- -----------------------------------------------------
-- Table `vendas_sucos`.`nova_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`nova_produtos` (
  `codigo` VARCHAR(10) NOT NULL,
  `descritor` VARCHAR(100) NULL DEFAULT NULL,
  `sabor` VARCHAR(50) NULL DEFAULT NULL,
  `tamanho` VARCHAR(50) NULL DEFAULT NULL,
  `embalagem` VARCHAR(50) NULL DEFAULT NULL,
  `preco_lista` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`produtos` (
  `codigo` VARCHAR(10) NOT NULL,
  `descritor` VARCHAR(100) NULL DEFAULT NULL,
  `sabor` VARCHAR(50) NULL DEFAULT NULL,
  `tamanho` VARCHAR(50) NULL DEFAULT NULL,
  `embalagem` VARCHAR(50) NULL DEFAULT NULL,
  `preco_lista` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`vendedores` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  `COMISSAO` FLOAT NULL DEFAULT NULL,
  `DATA_ADMISSAO` DATE NULL DEFAULT NULL,
  `FERIAS` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
